services:
    mongo:
        image: mongo:7.0
        container_name: my-mongodb
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_DATABASE: ${MONGODB_NAME}
        volumes:
            - mongo-data:/data/db

    redis:
        image: redis:7.2
        container_name: my-redis
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data

    app:
        build: .
        image: snacktrack
        container_name: snacktrack-app
        ports:
            - '3000:3000'
        depends_on:
            - mongo
            - redis
        env_file: .env.local
        volumes:
            - .:/app
        command: npm run dev

volumes:
    mongo-data:
    redis-data:
